pipeline {
    agent any

    environment {
        DOCKER_HUB_USERNAME = 'serenell4'
        IMAGE_NAME = "service-app"
        DOCKER_HUB_CREDENTIALS_ID = 'docker_password'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build and Test') {
            steps {
                script {
                    def gradleHome = tool 'gradle-8'
                    sh "${gradleHome}/bin/gradle clean build"
                }
            }
        }

        stage('Docker Build and Push') {
            steps {
                script {
                    def imageTag = "${DOCKER_HUB_USERNAME}/${IMAGE_NAME}:latest"
                    
                    sh "docker build -t ${imageTag} ."
                    
                    withCredentials([usernamePassword(credentialsId: "${DOCKER_HUB_CREDENTIALS_ID}", 
                                     passwordVariable: 'DOCKER_PASSWORD', 
                                     usernameVariable: 'DOCKER_USERNAME')]) {
                        sh "echo \$DOCKER_PASSWORD | docker login -u \$DOCKER_USERNAME --password-stdin"
                        sh "docker push ${imageTag}"
                    }
                }
            }
        }
    }
}
