global:
  resolve_timeout: 1m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1m
  receiver: 'comment-alerts-receiver'

receivers:
- name: 'comment-alerts-receiver'
  email_configs:
  - to: 'serenaprogetto17@gmail.com'
    from: 'alertmanager@monitoring.com'
    smarthost: 'smtp.gmail.com:587'
    auth_username: 'serenaprogetto17@gmail.com'
    auth_password: 'zspa uysu foii wpxs'
    require_tls: true